version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/google-credentials.json
    volumes:
      - ./secrets:/secrets:ro
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "8080:8080"  # HTTP para frontend
      - "8443:8443"  # HTTPS para backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
